### PR TITLE
add in all GL fields

### PR DESCRIPTION
**Pull request by srkirkland**
can now lookup GL acct.

### CODE REVIEW

**Review by sprucely — APPROVED** [review]

**Review by jSylvestre — CHANGES_REQUESTED** [review]
Purpose is 2 characters, so the lookup needing 3 isn't triggered

**Comment by jSylvestre** [comment]
- [ ] GL button doesn't get selected color even though page changes
- [ ] Search is only finding exact matches when looking for the code (maybe this is because the PPM stuff has the code in the name)?
- [ ] Purpose is only 2 characters, search isn't triggered unless you search the name

**Comment by srkirkland** [comment]
@jSylvestre search should only find exact matches for code, or at least that's how I intentionally wrote it.  Your purpose code comment is interesting though, I guess i'll have to parameterize the # chars required to handle that case.

**Comment by srkirkland** [comment]
@jSylvestre I fixed the other 2 things -- purpose code now just requires 2 chars for search, so entering a code directly will work

**Pull request merged**
